apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: busybox
        image: busybox
        # ports:
        # - containerPort: 8080
        command: ["sh","-c","while true; do echo 'Hello from Busybox'; sleep 5; done"]
