pipeline {
    agent {
        docker {
            image 'python:3.10'
            args '--privileged -v /var/run/docker.sock:/var/run/docker.sock'
        }
    }
    environment {
        DOCKERHUB_CREDENTIALS = credentials('docker-hub-creds')
        DOCKER_REGISTRY = 'morandan7'
        REPO_NAME = 'fe-exam'  // Change to 'be-exam' for backend pipeline
        IMAGE_TAG = "${env.BUILD_NUMBER}"
        
    }
    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'workshop/argo-jenkins-exam', url: 'https://github.com/MoranDanino/devopshift-welcome.git'
            }
        }

        stage('Lint & Security Scan'){
            parallel{
                stage('Flake8 Linting') {
                    steps {
                        sh 'pip install flake8'
                        sh 'flake8 . || true'
                    }
                }
                
                stage('Bandit Security Scan') {
                    steps {
                        sh 'pip install bandit'
                        sh 'bandit -r . || true'  
                    }
                }
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'ls -l'
                sh 'cd exam-code/docker/fe && pip install -r requirements.txt' 
            }
        }

        //add stage to handle error: Docker not found && download docker-compose
        stage('Install Docker'){
            steps{
                sh '''
                #install docker
                apt-get update
                apt-get install -y docker.io 
                docker --version

                #install docker-compose
                curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
                chmod +x /usr/local/bin/docker-compose
                /usr/local/bin/docker-compose --version
                '''
            }
        }

        stage('Build Docker Image'){
            steps {
                dir('exam-code/docker/fe') {
                    script {
                        sh 'docker build -t ${DOCKER_REGISTRY}/${REPO_NAME}:${IMAGE_TAG} .'
                        sh 'docker tag ${DOCKER_REGISTRY}/${REPO_NAME}:${IMAGE_TAG} ${DOCKER_REGISTRY}/${REPO_NAME}:${IMAGE_TAG}'
                    }
                }
            }
        }

        stage('Run Tests in Container'){
            steps{
                sh 'docker run --rm ${DOCKER_REGISTRY}/${REPO_NAME}:${IMAGE_TAG} pytest tests/'
            }
        }

        stage('Integration Test with Docker Compose'){
            steps {
                sh '''
                    pwd
                    ls -la 
                    cd exam-code/docker
                    ls -la
                    docker-compose -f docker-compose.yaml up -d
                    sleep 20
                    docker ps -a 
                    docker-compose -f docker-compose.yaml down
                '''
            }
        }


        // stage('Integration Test with Docker Compose'){
        //     steps {
        //         sh '''
        //             pwd
        //             ls -la 
        //             cd exam-code/docker
                    
        //             docker-compose -p fe-exam-integration down || true
        //             docker-compose -p fe-exam-integration up -d --build

        //             sleep 20
                    
        //             docker ps -a
                    
        //             WEB_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' fe-exam-integration-web-1)
        //             echo "Web container IP is: $WEB_IP"
                        
        //             # Try different curl approaches
        //             curl -v http://localhost:5011/ || echo "Failed to connect via localhost"
        //             curl -v http://$WEB_IP:5011/ || echo "Failed to connect via container IP"
                        
        //             # Check container port mappings
        //             docker port fe-exam-integration-web-1
                        
        //             # Check logs for potential issues
        //             docker logs fe-exam-integration-web-1
                    
        //             docker logs fe-exam-integration-backend-service-1 || true
        //             docker logs fe-exam-integration-mysqldb-1 || true
                    
        //             docker-compose -p fe-exam-integration down || true
        //         '''
        //     }
        // }

        stage('Push to Docker Hub'){
            steps{
                sh '''
                echo ${DOCKERHUB_CREDENTIALS_PSW} | docker login -u ${DOCKERHUB_CREDENTIALS_USR} --password-stdin
                docker push ${DOCKER_REGISTRY}/${REPO_NAME}:${IMAGE_TAG} 
                docker push ${DOCKER_REGISTRY}/${REPO_NAME}:latest
                '''
            } 
        }
    }

    post {
        always {
            echo 'Cleaning up workspace'
            deleteDir()
        }
        failure {
            echo 'Failed'
        }
        success {
            echo 'Success'
        }
    }

}
